collect_mentions_task:
  description: >
    Collect brand mentions for the company '{company_to_search}' focusing on keywords '{keywords_to_search}'
    over the last 7 days. Use the search_internet tool to find relevant discussions across web, news, 
    and social media platforms. Focus on gathering substantial content excerpts and context.
  expected_output: >
    A comprehensive compilation of 15-20 relevant brand mentions. Each mention should include:
    - Platform source (Web, News, Reddit, Twitter, etc.)
    - Content excerpt or summary of the discussion
    - Context about the conversation tone and topic

analyze_mentions_task:
  description: >
    Analyze the collected mentions to extract strategic insights. Calculate sentiment distribution
    (Positive, Negative, Neutral percentages). Identify 3-5 key themes or topics being discussed.
    Flag any critical negative mentions that require immediate attention. Focus on actionable insights.
  expected_output: >
    Detailed analysis containing:
    1. Sentiment breakdown with exact percentages
    2. Top 3-5 recurring themes with brief descriptions
    3. Critical alerts highlighting urgent issues
    4. Notable mention summaries for key conversations

generate_report_task:
  description: >
    Create a professional brand monitoring report in JSON format. Generate a comprehensive markdown
    report with executive summary, sentiment analysis, key themes, notable mentions, and strategic
    recommendations. Include chart data for visualization.
  expected_output: >
    Clean JSON object with this structure:
    {
      "report_markdown": "# Brand Monitoring Report for {company_to_search}\n\n**Executive Summary:**\n[Brief overview of findings]\n\n**Sentiment Analysis:**\n- Positive: X%\n- Negative: Y%\n- Neutral: Z%\n\n**Key Themes:**\n- Theme 1: Description\n- Theme 2: Description\n\n**Notable Mentions:**\n- Platform discussion summary\n- Key conversation highlights\n\n**Strategic Recommendations:**\n- Actionable recommendation 1\n- Actionable recommendation 2",
      "chart_data": {
        "sentiment": {"Positive": X, "Negative": Y, "Neutral": Z},
        "themes": [{"name": "Theme1", "mentions": N}]
      }
    }